"""Add active persona details to ChatMessage

Revision ID: 1122a859f9f3
Revises: 8c83f81e0ab6
Create Date: 2025-05-23 14:06:57.293766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1122a859f9f3'
down_revision: Union[str, None] = '8c83f81e0ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_lore', schema=None) as batch_op:
        batch_op.drop_index('ix_global_lore_title')

    op.drop_table('global_lore')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_persona_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('active_persona_image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('active_persona_image_url')
        batch_op.drop_column('active_persona_name')

    op.create_table('global_lore',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('global_lore', schema=None) as batch_op:
        batch_op.create_index('ix_global_lore_title', ['title'], unique=False)

    # ### end Alembic commands ###
