"""add chat_session and chat_message tables

Revision ID: 43a25705b730
Revises: 26589f75c33f
Create Date: 2025-05-12 23:18:07.115943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a25705b730'
down_revision: Union[str, None] = '26589f75c33f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('example_dialogues', sa.JSON(), nullable=True),
    sa.Column('beginning_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_cards_name'), 'character_cards', ['name'], unique=False)
    op.create_table('scenario_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('beginning_message', sa.Text(), nullable=True),
    sa.Column('world_card_references', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_cards_name'), 'scenario_cards', ['name'], unique=False)
    op.create_table('user_personas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_personas_name'), 'user_personas', ['name'], unique=False)
    op.create_table('world_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('card_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_cards_card_type'), 'world_cards', ['card_type'], unique=False)
    op.create_index(op.f('ix_world_cards_name'), 'world_cards', ['name'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('gm_character_id', sa.String(), nullable=False),
    sa.Column('user_persona_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['gm_character_id'], ['character_cards.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario_cards.id'], ),
    sa.ForeignKeyConstraint(['user_persona_id'], ['user_personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chat_session_id', sa.String(), nullable=False),
    sa.Column('sender_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_user_settings_id', table_name='user_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_settings_id', 'user_settings', ['id'], unique=False)
    op.drop_table('chat_messages')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_world_cards_name'), table_name='world_cards')
    op.drop_index(op.f('ix_world_cards_card_type'), table_name='world_cards')
    op.drop_table('world_cards')
    op.drop_index(op.f('ix_user_personas_name'), table_name='user_personas')
    op.drop_table('user_personas')
    op.drop_index(op.f('ix_scenario_cards_name'), table_name='scenario_cards')
    op.drop_table('scenario_cards')
    op.drop_index(op.f('ix_character_cards_name'), table_name='character_cards')
    op.drop_table('character_cards')
    # ### end Alembic commands ###
