"""Remove ai_plan column and obsolete tables for simplified flow

Revision ID: c4a8ad1b4cda
Revises: 6a9a0ab3fc70
Create Date: 2025-06-02 13:55:14.011202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c4a8ad1b4cda'
down_revision: Union[str, None] = '6a9a0ab3fc70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('full_analysis_results')
    with op.batch_alter_table('global_lore', schema=None) as batch_op:
        batch_op.drop_index('ix_global_lore_title')

    op.drop_table('global_lore')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('ai_plan')

    with op.batch_alter_table('extracted_knowledge', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('chat_session_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('source_message_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_knowledge', schema=None) as batch_op:
        batch_op.alter_column('source_message_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('chat_session_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_plan', sqlite.JSON(), nullable=True))

    op.create_table('global_lore',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('global_lore', schema=None) as batch_op:
        batch_op.create_index('ix_global_lore_title', ['title'], unique=False)

    op.create_table('full_analysis_results',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('chat_session_id', sa.NUMERIC(), nullable=False),
    sa.Column('source_message_id', sa.NUMERIC(), nullable=False),
    sa.Column('analysis_data', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['source_message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
