# D:\VSCode\advanced-roleplay-engine\backend\alembic\versions\f24fd9dcd372_add_faction_id_to_world_cards.py

"""add faction_id to world_cards

Revision ID: f24fd9dcd372
Revises: 43a25705b730 # <-- Verifique se 'Revises' aponta para a migração anterior correta
Create Date: <Data de Criação>

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24fd9dcd372'
down_revision: Union[str, None] = '43a25705b730' # <-- Verifique este ID
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faction_id', sa.String(), nullable=True))
        # O nome da constraint pode ser gerado automaticamente ou você pode nomeá-la
        # Nomear é bom para o downgrade, mas 'None' também funciona.
        # O Alembic pode gerar um nome como 'fk_world_cards_faction_id_world_cards'
        batch_op.create_foreign_key(
            'fk_world_cards_faction_id_world_cards', # Nome da constraint (pode ser None)
            'world_cards', # Tabela referenciada
            ['faction_id'], # Coluna local
            ['id'] # Coluna remota
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_cards', schema=None) as batch_op:
        # Remove a chave estrangeira primeiro (precisa do nome da constraint)
        # Se você usou None no upgrade, você precisará descobrir o nome que o SQLite deu
        # ou que o Alembic usou internamente (pode ser complicado).
        # É por isso que nomear a constraint no upgrade é útil.
        # Assumindo que o nome é 'fk_world_cards_faction_id_world_cards':
        batch_op.drop_constraint('fk_world_cards_faction_id_world_cards', type_='foreignkey')
        batch_op.drop_column('faction_id')
    # ### end Alembic commands ###